language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine curl

install:
  # Install the latest Ansible Container and Ansible
  - pip install git+https://github.com/ansible/ansible-container.git
  - pip install ansible

script:
  # Make sure docker is functioning
  - docker version
  - docker-compose version
  - docker info

  # Create an Ansible Container project
  - mkdir -p tests
  - cd tests
  - ansible-container init

  # Install the role into the project
  - echo "Installing and testing git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}"
  - ansible-container install git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}

  # Install dependency
  - ansible-container install git+https://github.com/chouseknecht/mariadb-container

  - curl https://raw.githubusercontent.com/awasilyev/drupal-container/master/tests/container.yml >ansible/container.yml
 
  # Build the service image
  - ansible-container build

  # Start the service
  - ansible-container run -d 
  - docker logs ansible_apache_1

  # Run tests
  - ansible-playbook test.yml
  
  - docker logs ansible_apache_1

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

