---
- name: Install Drush
  get_url: dest=/usr/bin/drush mode=755 url='https://s3.amazonaws.com/files.drush.org/drush.phar'

# Download Drupal using drush (--no-cache prevents checksum error).
#- name: "Drupal: Download Drupal Core."
#  command:
#     drush dl drupal-{{ drupal_core_version }} --no-cache
#     creates={{ drupal_core_path }}/index.php
#     chdir={{ drupal_core_path }}

- name: Remove existing /var/www/html
  file: name=/var/www/html state=absent 

# Download Drupal using Git.
- name: Check out Drupal Core to the default location.
  git:
    repo: "{{ drupal_repo_url }}"
    version: "{{ drupal_core_version }}"
    update: "{{ drupal_keep_updated }}"
    dest: "{{ drupal_core_path }}"

#- name: Install Drupal.
#  shell: > 
#    cd {{ drupal_core_path }};
#    yes | drush si {{ drupal_install_profile }} -y
#    --site-name="{{ drupal_site_name }}"
#    --account-name={{ drupal_admin_name }}
#    --account-pass={{ drupal_admin_password}}
#    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Set permissions properly on settings.php.
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: 0744
    owner: apache
    state: touch

- name: Set permissions properly on files directory.
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes

- name: Add entrypoint script
  template:
   src: entrypoint.sh.j2
   dest: /usr/bin/entrypoint.sh
   owner: root
   group: root
   mode: 0775

- name: Add main config
  template: 
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf


