---
- name: Create hosts entry for domain.
  lineinfile:
    dest: "{{ drupal_hosts_file_path }}"
    regexp: "^127.0.0.1    {{ drupal_domain }}"
    line: "127.0.0.1    {{ drupal_domain }}"
    state: present
  when: drupal_hosts_file_path is defined and drupal_hosts_file_path
