---
- name: Install dumb init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/bin/dumb-init
    owner: root
    group: root
    mode: 0775

- name: Add entrypoint script
  template:
   src: entrypoint.sh.j2
   dest: /usr/bin/entrypoint.sh
   owner: root
   group: root
   mode: 0775

- name: Add main config
  template: 
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: Add includes to config
  template: 
    src: "{{item}}.j2"
    dest: "/etc/httpd/conf.d/{{item}}"
  with_items:
    - ssl.conf
    - vhost.inc

- name: Set directory ownership 
  file: name="{{item}}" state=directory owner=apache group=root mode=0775
  with_items:
  - /run/httpd
  - /etc/httpd/ssl
  - /var/www/html

